# This is a basic workflow to help you get started with Actions

name: CI
on:
  schedule:
  - cron: "* * * * *"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install #will run `yarn install`
      - uses: borales/actions-yarn@v2.0.0
        with: 
          cmd: generate # will run `yarn generate` command
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
